### ISSUE TITLE
Tilføj beskrivelse til rejse

### ISSUE THREAD

**Issue by Fire-Proof** [Spurux/MiniProjekt2#5]

**Comment by Spurux** [comment]
@Fire-Proof @ndlarsen, jeg tænker at vi blot sætter `android:autoLink="web"` på vores `TextView`, i stedet for at begynde at rode med en masse rich text ting og sager. Den jeg kigger på lige nu er ret voldsom, og kræver ekstremt meget arbejde af os. Den der løsning er lidt lettere, og meget mere lige til - den burde selv kunne finde ud af at konvertere et link til et klikbart link. 😀
