### ISSUE TITLE
Potentiel bug i journeyLV.setOnItemClickListener?

### ISSUE THREAD

**Issue by Fire-Proof** [Spurux/MiniProjekt2#7]
Er der her ID altid lig med det ID den har i databasen? Eller er den indikere den et id man får fra adapteren?

https://github.com/Spurux/MiniProjekt2/blob/b56e294f39c8ca97ce40242b9aaef1fee54819a3/app/src/main/java/dk/mahj/miniprojekt2/MainActivity.java#L45-L48

**Comment by Spurux** [comment]
Yes, for cursoradapteren er det altid det samme som i databasen. (Jeg svare udelukkende for sjovs skyld, siden vi allerede har taget den i klassen :D)
